apiVersion: v1
kind: Pod
metadata:
  labels:
    role: webhook
  name: webhook
spec:
  containers:
    - name: webhook
      image: onyinyang/clusterregistry-admission-server:latest
      imagePullPolicy: IfNotPresent
      ports:
- containerPort: 8000
